language: node_js
services:
- docker
cache:
  directories:
  - ~/.nvm
  - node_modules
env:
  global:
  - RELEASE_BRANCH="master"
  - DOCKER_HUB_ACCOUNT=edenlabllc
  - MAIN_BRANCHES="master develop"
  - secure: "z6nJvNguEoXIALhrqo1dzVYQiQXkVeDmHJYgR8FMLuwU9YmyaNuTzngIhyp0uWo+d8nukKG0RmN0lz5Ns6vlooX9hAYhzsVNB+ODT8ZcHRMC8RooenAScVHuBzFYd6guRX2J6uT2LvI3v5SqZPmmATyBCM0vOkQK3mK4avnJ4N/5tuwclJqz1Hdy3IaGaLER43auARS71ARQ0QW9WW7G8SgRbMdJZhLvH16DEfeP2J9TvDmna+fJRNjwgcjszyRVf3YLctJIY4Kv9lGwopktCmvBL6jcgng454Bk/qoybnBHsopGOw3Mw/NayhoecwKujEEW2VB6t23JpPCgZua85JvraBG4SjhcND1xmEd+x34caUk0SCNgqARj/4ILVkdYjzZp9VfqS4LmZ5FRpEHPH4r9ccYJroxXb1zCSR5TTb2GgsTDc6abSAUIzpwm7R1djrz4L6mrzozBuAnFgIYi/rZy/VE9bdI4imlpqgLO3j/KOaghaxfyFNwCB2apUB/s1QJ28PcR5LDNkj+8Hl4azVAFPs3LhzNFpjt6f1XMDRCJdSFfy5RQGsZJ8WdHbOUex14RGFv9XRfbM5x7/O/bIdImY5uZKoAT8a3YEp5E7MJBimWtMmWk4B/zJeDYH53qZuPZBUAclZ98ETrG6GkzCb2eGq2cvoGEp4yPQ/5hZVA="
  - secure: "NIeT94JGVFC+O6M8y4Uy4/tP8W761Qq+nMtWthp+MMRrYKmkUyqKe9oiuBYHjlJoPx0hxlSCaNaIrdLe58NX1+8kaO8wXCgVA/ikkUd/tqkQ3Ho0g+82475TK82xf+eHVYzZmfu/FVyjlP2ZuTJagij4DiojNybH0XuvarcjjMacIRQ/tM5WKNt15jWT9J9EOs4/7efk9lU2kYAEYnfa5AxBTVlMtEjKRgf9ULpze4kgOS6vL2em/L5Q4faHqivGM2lzN6OSL9auHMSMhuqm02AfNrD4vkE1T2/j+vkr6F+TSHm7T/K3/EDZINgL7IFNz9xoS5xQIxOZvhwaJXje/7HBmFc17z/Uu68vEeNlIXBoO07Fjt8rlIzNHF9Axgtfk4itPKv6Zy3uQIxpqEy+nD89N/yvk4CLsjqII8dSNws3pMpNFK9+I4VnvOfZPcKj3Pmpy6fbuk/2KtOgbt9ZEx9fI7wJfUSiiATnn+QkumNyfGrvOYf+I2h/KNZMR7FIUwfzyPfHlfebveXfveZ4Yegmwe48vbuTTNBk9JuUR7g4FuXpw9wH3uGZ/p+6YnseTJ9vi1s3FbLXOgLhmnDmMQcdibEL3kTcW+tlT48LTRfKqavSXFldqLD3wuAhtLCYFjelbuV/kICLq/ta00NM1r/bstUuQEX9EW8v200OSTU="
node_js:
- 6.9.1
before_install:
- npm run docker:up
- chmod -R +x bin
script:
- npm run test
- npm run lint
- ./bin/version-increment.sh
- ./bin/build.sh
- ./bin/start.sh
- docker-compose -f ./docker/dc.travis.yml up -d
- sleep 5
- docker ps
- RUNNING_CONTAINERS=`docker ps | wc -l`;
  if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "1" ]; then
    echo "[E] Container is not started\!";
    docker logs annon.web --details --since 5h;
    exit 1;
  fi;
- npm run nightwatch -- -e travis
- sleep 5
after_success:
- ./bin/ci/push.sh
