language: node_js
services:
- docker
cache:
  directories:
  - ~/.nvm
  - node_modules
notifications:
  slack: 
    rooms:
      - secure: "cBhMVDtlBd/Q39uQpTwbNnhd1Be/KYuSmaxBwvW0gJgMWkMRhoEWuKgkV+l1sVTvTSmHPRqDI7rOCfKlqkvGjwOFaHft9TJU3HbnyuxC2sfH7LSK865DTlefzt0umKMgIYEyaX97dN8fjt8q2TCNRCwBLpTxR4wMEwbC99JgnerKu1HmgWJffNX2PS+t5CihERsoOrCbtWZT7r1dWcq6jm//HA7DY/TA3lJMk3yo7bRSh1Zlm7elB4i8/KuZrhUa3O5Nuy8k2xc3vu1QXtOAX8Jf6ABC0ByXvg3XKqakhtmxJvLFApHzfZZ8EAyaBjdoEogO7iY3+0bCht+0itzTlxATq2PXm/MzEIINdBHo5409UWJscAR6BzyFgmqxCrbbNZ0YVMN4lRrWaSg/WfDcw2kGUx4s5eJ5Vt2l7DJn8slVqt8W7yb8OS1PuEz+pleWChmL2nhqc3NYA0ufAskJI2goBbsmCrgx9c2mJLFq8rvPB+HxIA9h3XzQ9xZE5xanC+KXGYCV9z4Sxaq/xQeFtgsGHmjjuVWzDijvFza/eT78taiApt3fhCAvHDsHJs2txJk2MFo8QrYdXWhKqzUNKB2F7o0b54fjYZ3vvKhiNgpOKrpZm4/9QgVKMFddeVKbC5Set3OpOb0QF/QV3fhaMWQOgLnR7m4DEUWK7AaZXkw="
    on_success: always
env:
  global:
  - Chart=gateway
  - RELEASE_BRANCH="master"
  - DOCKER_HUB_ACCOUNT=edenlabllc
  - MAIN_BRANCHES="master develop"
  - secure: "z6nJvNguEoXIALhrqo1dzVYQiQXkVeDmHJYgR8FMLuwU9YmyaNuTzngIhyp0uWo+d8nukKG0RmN0lz5Ns6vlooX9hAYhzsVNB+ODT8ZcHRMC8RooenAScVHuBzFYd6guRX2J6uT2LvI3v5SqZPmmATyBCM0vOkQK3mK4avnJ4N/5tuwclJqz1Hdy3IaGaLER43auARS71ARQ0QW9WW7G8SgRbMdJZhLvH16DEfeP2J9TvDmna+fJRNjwgcjszyRVf3YLctJIY4Kv9lGwopktCmvBL6jcgng454Bk/qoybnBHsopGOw3Mw/NayhoecwKujEEW2VB6t23JpPCgZua85JvraBG4SjhcND1xmEd+x34caUk0SCNgqARj/4ILVkdYjzZp9VfqS4LmZ5FRpEHPH4r9ccYJroxXb1zCSR5TTb2GgsTDc6abSAUIzpwm7R1djrz4L6mrzozBuAnFgIYi/rZy/VE9bdI4imlpqgLO3j/KOaghaxfyFNwCB2apUB/s1QJ28PcR5LDNkj+8Hl4azVAFPs3LhzNFpjt6f1XMDRCJdSFfy5RQGsZJ8WdHbOUex14RGFv9XRfbM5x7/O/bIdImY5uZKoAT8a3YEp5E7MJBimWtMmWk4B/zJeDYH53qZuPZBUAclZ98ETrG6GkzCb2eGq2cvoGEp4yPQ/5hZVA="
  - secure: "NIeT94JGVFC+O6M8y4Uy4/tP8W761Qq+nMtWthp+MMRrYKmkUyqKe9oiuBYHjlJoPx0hxlSCaNaIrdLe58NX1+8kaO8wXCgVA/ikkUd/tqkQ3Ho0g+82475TK82xf+eHVYzZmfu/FVyjlP2ZuTJagij4DiojNybH0XuvarcjjMacIRQ/tM5WKNt15jWT9J9EOs4/7efk9lU2kYAEYnfa5AxBTVlMtEjKRgf9ULpze4kgOS6vL2em/L5Q4faHqivGM2lzN6OSL9auHMSMhuqm02AfNrD4vkE1T2/j+vkr6F+TSHm7T/K3/EDZINgL7IFNz9xoS5xQIxOZvhwaJXje/7HBmFc17z/Uu68vEeNlIXBoO07Fjt8rlIzNHF9Axgtfk4itPKv6Zy3uQIxpqEy+nD89N/yvk4CLsjqII8dSNws3pMpNFK9+I4VnvOfZPcKj3Pmpy6fbuk/2KtOgbt9ZEx9fI7wJfUSiiATnn+QkumNyfGrvOYf+I2h/KNZMR7FIUwfzyPfHlfebveXfveZ4Yegmwe48vbuTTNBk9JuUR7g4FuXpw9wH3uGZ/p+6YnseTJ9vi1s3FbLXOgLhmnDmMQcdibEL3kTcW+tlT48LTRfKqavSXFldqLD3wuAhtLCYFjelbuV/kICLq/ta00NM1r/bstUuQEX9EW8v200OSTU="
node_js:
- 6.9.1
before_install:
- openssl aes-256-cbc -K $encrypted_aebc322adf79_key -iv $encrypted_aebc322adf79_iv -in eHealth-eef414faa06b.json.enc -out eHealth-eef414faa06b.json -d
- npm run docker:up
- chmod -R +x bin
script:
- npm run test || travis_terminate 1
- npm run lint || travis_terminate 1
- ./bin/version-increment.sh || travis_terminate 1
- ./bin/build.sh || travis_terminate 1
- ./bin/start.sh || travis_terminate 1
- docker-compose -f ./docker/dc.travis.yml up -d || travis_terminate 1
- sleep 5
- docker ps
- RUNNING_CONTAINERS=`docker ps | wc -l`;
  if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "1" ]; then
    echo "[E] Container is not started\!";
    docker logs annon.web --details --since 5h;
    exit 1;
  fi;
- npm run nightwatch -- -e travis || travis_terminate 1
- sleep 5
- "./bin/ci/push.sh || travis_terminate 1 " 
- sudo ./bin/deploy.sh || travis_terminate 1
